[package]
name = "wgpu-tutorial"
version = "0.1.0"
authors = ["Ben Hansen <https://github.com/sotrh>"]
edition = "2021"

[dependencies]
cfg-if = "1"
winit = { version = "0.29" }
env_logger = "0.11.8"
log = "0.4"
wgpu = "25.0"
pollster = "0.4.0"
